events {}

http {
  upstream backend_php {
    server backend:9000;
  }

  server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    location / {
      try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_pass backend_php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
  }
}
